name:                asato
version:             0.1.0.0
github:              "chocolatier/asato"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "none"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/chocolatier/asato#readme>

dependencies:
- base >= 4.7 && < 5
- themoviedb >= 1.1.5.0
- text >= 1.2.3.1
- yaml >= 0.11.0.0
- aeson >= 1.4.2.0

library:
  source-dirs: src

executables:
  asato-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - asato

tests:
  asato-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - asato
